### PR TITLE
Add additional keywords to colorization list

### PR DESCRIPTION
**Pull request by kburtram**
Add additional keywords to colorization list, specifically USE, RESTORE, TO, and FILE.

### CODE REVIEW

**Comment by llali** [comment]
:shipit:

**Comment by borgdylan** [comment]
Can we also add ```FUNCTION``` and ```RETURN```. TVFs are not highlighted correctly.
image

**Comment by kburtram** [comment]
@borgdylan thanks!  I've added those missing keywords as well.

**Comment by borgdylan** [comment]
Thank you.

**Pull request merged**
