### PR TITLE
bring results of respective editor when query is run

### PR DESCRIPTION
**Pull request by abist**
Fixes https://github.com/microsoft/vscode-mssql/issues/1332

Addresses https://github.com/microsoft/vscode-mssql/issues/1319 by showing the "Toggle SQLCMD Mode" only when editor has focus, and thus not being confusing any more. Then there are 3 cases -
1. Editor file is .sql and connected - command runs
2. Editor file is .sql and not connected - editor asks to connect to run command
3. Editor file is not .sql - show info message that a .sql file is required to run the command

Fixes https://github.com/microsoft/vscode-mssql/issues/1327

### CODE REVIEW

**Comment by Charles-Gagnon** [comment]
>     private _isDisposed: boolean = false;

This is already a disposable - you should be calling this._register to register the disposables instead. Then adding your own dispose method is unnecessary

---
Refers to: src/controllers/webviewController.ts:30 in 3207fff. [](commit_id = 3207fffc1dc19d47c14dc9b8e9b715119c443cf8, deletion_comment = False)

**Comment by Charles-Gagnon** [comment]
>     private _isDisposed: boolean = false;

Since you're using the isDisposed as well there's two options to solve that :

1. Override dispose() and add setting isDisposed but then still call super.dispose();
2. Find out where the controller is being disposed and remove it from the map at that point instead of waiting until the query callback is called (this seems like the more correct approach)

---
In reply to: [535534137](https://github.com/microsoft/vscode-mssql/pull/1334#issuecomment-535534137) [](ancestors = 535534137)

---
Refers to: src/controllers/webviewController.ts:30 in 3207fff. [](commit_id = 3207fffc1dc19d47c14dc9b8e9b715119c443cf8, deletion_comment = False)

**Comment by abist** [comment]
@Charles-Gagnon This class is implementing it, not extending it. The only way the panel gets disposed is when it's closed. So, `super.dispose()` doesn't work as it's our class.

**Comment by Charles-Gagnon** [comment]
Huh. Why are you implementing it instead of extending? Seems like we're just duplicating code for no real reason.

**Comment by abist** [comment]
@Charles-Gagnon this is `vscode.Disposable` which is different from the `Disposable` class we use in ADS which is which a wrapper for this class - https://github.com/microsoft/azuredatastudio/blob/master/extensions/mssql/src/util/dispose.ts

**Pull request merged**
