### PR TITLE
Making spinner visible until query completion

### PR DESCRIPTION
**Pull request by benrr101**

### CODE REVIEW

**Comment by anthonydresser** [comment]
Did you consult this with @erickangMSFT ? We weren't doing this intentionally.

**Comment by benrr101** [comment]
Yep, I consulted with @erickangMSFT before I made the change. I'll verify with him that this change is suitable.

**Comment by erickangMSFT** [comment]
I checked the UX on the dev build and signed-off.

**Comment by anthonydresser** [comment]
@erickangMSFT what do you mean checked on dev build? these changes are not on the dev branch yet.

**Comment by benrr101** [comment]
I think he means he checked the build on my developer machine

**Pull request merged**
