### PR TITLE
Editor/icons

### PR DESCRIPTION
**Pull request by abist**
Fixes https://github.com/microsoft/vscode-mssql/issues/1443#issuecomment-567272699

Capture

### CODE REVIEW

**Comment by abist** [comment]
@anthonydresser These icons are theme based, and from ADS. What do you mean by using our own icons?

**Comment by anthonydresser** [comment]
> @anthonydresser These icons are theme based, and from ADS. What do you mean by using our own icons?

vscode recently added the ability to specify icons coming from the icon theme the user is using, rather than providing your own. This adds greater theme awareness other than just light/dark.

**Comment by abist** [comment]
@anthonydresser will look into it!

**Comment by anthonydresser** [comment]
It might still be in preview, https://github.com/microsoft/vscode/blob/master/src/vs/platform/actions/common/actions.ts#L26

I just remember seeing it.

**Comment by anthonydresser** [comment]
e.x you could utilize the same icon as what is being used in the debugger. looks like the id for start there is `codicon-debug-start`

**Pull request merged**
