### PR TITLE
Fix issue with disconnect node

### PR DESCRIPTION
**Pull request by abist**
Fixes https://github.com/microsoft/vscode-mssql/issues/1404

### CODE REVIEW

**Comment by abist** [comment]
@amitmsft How so?

**Comment by aaomidi** [comment]
Wrong @ btw, but since you're doing recursion you're going to be filling the stack pretty fast.

If each node has 10 children and you're going 3 layers deep that is a 1000 element long stack and JS will not work with that.

**Comment by abist** [comment]
We handle thousands of files recursively when using gulp tasks and packaging but that's fine. I'll put put an iterative one in a moment,

**Comment by aaomidi** [comment]
Put this in chrome and see what happens:

```
function fibonacci(num) {
  if (num <= 1) return 1;

  return fibonacci(num - 1) + fibonacci(num - 2);
};

fibonacci(1000)
```

The recursive handling of files lead us to the EMFILE error yesterday. It's bad practice.

**Pull request merged**
