### PR TITLE
Import correct stylings

### PR DESCRIPTION
**Pull request by cssuh**
Fixes cell size alignment (the text is more centered in the after view) and adds correct imported images
Also moves some files into reactViews

Before:
Screenshot 2024-09-19 at 9 37 50 AM

After:
Screenshot 2024-09-19 at 9 36 54 AM

### CODE REVIEW

**Comment by aasimkhan30** [comment]
@cssuh What are the icons for?

**Comment by cssuh** [comment]
> @cssuh What are the icons for?

They're for the filtering & sorting plugin and they're currently imported by the table.css file, so that's why I added them.

**Comment by cssuh** [comment]
Screenshot 2024-09-19 at 9 56 07 AM

This is how they will be used, I just haven't finished the plugin for them yet.

**Comment by aasimkhan30** [comment]
@cssuh, I see. Could you move the React resources to the `reactviews` folder? Currently, the files in the `media` folder are being copied directly into the VSIX, and the bundle also includes these files, causing duplication of resources.

**Comment by cssuh** [comment]
> @cssuh, I see. Could you move the React resources to the `reactviews` folder? Currently, the files in the `media` folder are being copied directly into the VSIX, and the bundle also includes these files, causing duplication of resources.

Sure, I'll move them

**Review by caohai — APPROVED** [review]

**Review by aasimkhan30 — APPROVED** [review]
Thanks for moving the files.

**Pull request merged**
