### PR TITLE
Fix query results font family

### PR DESCRIPTION
**Pull request by cheenamalhotra**
Fixes https://github.com/microsoft/vscode-mssql/issues/1730

Following PR https://github.com/microsoft/vscode-mssql/pull/1511 to make results font family work

image

### CODE REVIEW

**Review by Charles-Gagnon — APPROVED** [review]
What's it look like if the setting is cleared (empty) or invalid text is entered?

**Comment by cheenamalhotra** [comment]
> What's it look like if the setting is cleared (empty) or invalid text is entered?

It defaults to a serif system font..

image

**Review by kisantia — APPROVED** [review]

**Comment by iskeld** [comment]
This is still not working 

```
Extension version: v1.22.1
OS: macOS 14.4.1
VSCode: Version: 1.88.1
Commit: e170252f762678dec6ca2cc69aba1570769a5d39
Date: 2024-04-10T17:43:08.196Z (1 wk ago)
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Darwin arm64 23.4.0
```

Also, if the field is blank it should use the editor's font as it is stated in the description not a default system serif font

**Comment by marcelogmonteiro** [comment]
Any updates? Still not working

**Comment by cosmoKenney** [comment]
Same issue here. Even when I clear the setting value and restart VS Code, nothing changes. I have also tried just using a single font name: `Consolas`.
SQL Server Extension Version: v1.26.0
VS Code Version: 1.95.3 (user setup)
Commit: f1a4fb101478ce6ec82fe9627c43efbf9e98c813
Date: 2024-11-13T14:50:04.152Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Windows_NT x64 10.0.22631

**Pull request merged**
