### PR TITLE
Update tools service with updated sqlclient

### PR DESCRIPTION
**Pull request by abist**
Fixes https://github.com/microsoft/vscode-mssql/issues/1454

### CODE REVIEW

**Comment by Charles-Gagnon** [comment]
Are you going to update https://github.com/microsoft/vscode-mssql/blob/383200bfdbfab85ae0874f41e15f2862e1802a3d/src/configurations/production.config.json separately?

(is there any particular reason we do this anyways? Seems like needless overhead to upload to download center)

**Comment by abist** [comment]
@Charles-Gagnon the version in that file doesn’t matter apparently and is only used for signed downloads of the service for production bits.

**Comment by Charles-Gagnon** [comment]
So we just update the zip there instead of creating a new fwlink? What about users who don't update right away - couldn't that break them if they try to redownload the service?

**Comment by abist** [comment]
The link to the zip is created by some other process that Karl drives. For the new release, he will have to create new links.

**Pull request merged**
