### PR TITLE
Added support for Apple Silicon

### PR DESCRIPTION
**Pull request by davemcdermid**
Updated platform to support Apple Silicon (arm64).
Fixes issue 16967

### CODE REVIEW

**Review by leighghunt — APPROVED** [review]
Not sure if I have the power to "approve" as such, but I built Dave's code and I now have a functioning mssql extension on my M1 Mac. Thanks.

**Review by nazgu1 — APPROVED** [review]

**Review by rontrolard — APPROVED** [review]

**Review by kburtram — APPROVED** [review]
LGTM.  we're not build a copy of SQL Tools Service specifically for ARM, so does this mean the Intel build of those binaries are able to run on Apple Silicon systems?  (I don't have access to a machine with this chipset to verify)

**Comment by kburtram** [comment]
@abist could you please work with @davemcdermid to merge assuming this correctly enables support for Apple Silicon systems?

**Comment by davemcdermid** [comment]
Yep, SQL Tools seems to run just fine under Rosetta2. Not tested extensively, but so far it's been good for me.

**Comment by abist** [comment]
@davemcdermid Thanks for the PR! Like @kburtram mentioned, the service behind the extension uses Intel build binaries, so let me test out all the features and let's get it in once we confirm it all works as expected 😃

**Comment by davemcdermid** [comment]
Thanks @kburtram @abist

**Comment by mkellerman** [comment]
*Bump* Who has the power to merge this in?

**Comment by kburtram** [comment]
@abist I don't see any reason not to merge this.  Are you waiting on anything with this?

**Comment by fonnesbeck** [comment]
Can a release be created so that this fix is available to M1 users?

**Comment by mikeelston** [comment]
does this run native on apple silicon? or does it require rosetta?

**Comment by davemcdermid** [comment]
@mikeelston The fix was to continue to use Intel (x64) builds for SQL tools when the extension is running in VSCode natively on Apple Silicon. So, the extension is running natively, but the tools it runs are running under Rosetta2

**Pull request merged**
