### PR TITLE
Add query execution time to status bar

### PR DESCRIPTION
**Pull request by cssuh**
Adds the query execution time to the status bar
StatusBar

### CODE REVIEW

**Comment by lewis-sanchez** [comment]
What does it look like for queries that take longer to complete execution?

Run it with something like `WAITFOR DELAY '00:00:02';`

**Comment by cssuh** [comment]
> What does it look like for queries that take longer to complete execution?
> 
> Run it with something like `WAITFOR DELAY '00:00:02';`

What are you looking to see? I run it with a 1 second delay in the GIF - it just has the old query execution time until the query finishes and it updates the status bar with the new time

**Comment by lewis-sanchez** [comment]
I saw that after I made the gif larger. It just updates on completion.

**Review by lewis-sanchez — APPROVED** [review]

**Comment by caohai** [comment]
What's that spinning thing in the status bar? I guess it's an unrelated item?

**Comment by cssuh** [comment]
> What's that spinning thing next to the execution time in the status bar? I guess it's unrelated? image

yeah that is some copilot thing, so unrelated to this change

**Review by caohai — APPROVED** [review]

**Pull request merged**
